language: python
python:
  - '3.5'

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"

# safelist
branches:
  only:
    - staging

services:
  - postgresql

script:
  - ./manage.py test